version: "3.5"

services:
  database:
    image: postgres:14-alpine
    hostname: mybank_pg
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=mybank_db"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - "mybank_volume:/var/lib/postgresql/data/pgdata"
    networks: 
      - mybank_network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 512M

  admin:
    image: dpage/pgadmin4
    hostname: mybank_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=thiagoabdul10@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5433:80"
    networks:
      - mybank_network

  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: mybank_api01
    environment:
      - DB_CONNECTION_STRING=Host=mybank_pg; Database=mybank_db; Username=root; Password=root
      - RABBIT_HOST=mybank_rabbitmq
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
    ports:
      - "7002:80"
    networks:
      - mybank_network

  api02:
    <<: *api
    hostname: mybank_api02
    ports:
      - "7003:80"

  broker:
    image: rabbitmq:3-management
    hostname: mybank_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - mybank_network
    restart: unless-stopped
      
  loadbalancer:
    image: nginx
    hostname: mybank_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mybank_network
    depends_on:
        - api01
        - api02
  
  mongo:
    image: mongo
    hostname: mybank_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mybank_mongo_volume:/data/db
    networks:
      - mybank_network

networks:
  mybank_network:
    name: mybank_network

volumes:
  mybank_volume:
  mybank_mongo_volume: