version: "3.5"

services:
  database:
    image: postgres:14-alpine
    hostname: mybank_pg
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=mybank_db"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - "mybank_volume:/var/lib/postgresql/data/pgdata"
    networks: 
      - mybank_network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 512M

  admin:
    image: dpage/pgadmin4
    hostname: mybank_pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=thiagoabdul10@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5433:80"
    networks:
      - mybank_network

  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: mybank_api01
    environment:
      - DB_CONNECTION_STRING="Host=mybank_pgadmin4; Database=mybank_db; Username=root; Password=root"
    ports:
      - "7001:80"
    expose:
      - "80"
    networks:
      - mybank_network

  api02:
    <<: *api
    hostname: mybank_api02
    ports:
      - "7002:80"

  loadbalancer:
    image: nginx
    hostname: mybank_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mybank_network
    depends_on:
        - api01
        - api02

networks:
  mybank_network:
    name: mybank_network

volumes:
  mybank_volume: